SECTION "Title Tiles", ROM0

TitleTile1:
  db $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F
TitleTile2:
  db $FE, $FE, $FE, $FE, $E2, $E2, $F2, $F2, $0A, $0A, $06, $06, $02, $02, $00, $00
TitleTile3:
  db $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $5F, $5F, $7F, $7F, $7F, $7F, $FF, $FF
TitleTile4:
  db $00, $00, $00, $00, $00, $00, $00, $00, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
TitleTile5:
  db $E0, $E0, $C0, $C0, $80, $80, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
TitleTile6:
  db $E0, $E0, $F8, $F8, $3C, $3C, $9E, $9E, $CE, $CE, $4E, $4E, $4F, $4F, $4F, $4F
TitleTile7:
  db $07, $07, $03, $03, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
TitleTile8:
  db $4F, $4F, $4F, $4F, $4F, $4F, $4F, $4F, $9F, $9F, $3F, $3F, $FF, $FF, $FF, $FF
TitleTile9:
  db $00, $00, $00, $00, $00, $00, $80, $80, $C0, $C0, $E0, $E0, $F0, $F0, $F8, $F8
TitleTile10:
  db $00, $00, $01, $01, $06, $06, $09, $09, $13, $13, $13, $13, $27, $27, $27, $27
TitleTile11:
  db $3F, $3F, $FF, $FF, $FF, $FF, $FC, $FC, $F0, $F0, $C0, $C0, $80, $80, $80, $80
TitleTile12:
  db $F0, $F0, $FC, $FC, $FF, $FF, $3F, $3F, $07, $07, $01, $01, $00, $00, $00, $00
TitleTile13:
  db $00, $00, $20, $20, $E0, $E0, $60, $60, $20, $20, $A0, $A0, $E0, $E0, $60, $60
TitleTile14:
  db $00, $00, $00, $00, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $00, $00
TitleTile15:
  db $08, $08, $18, $18, $E8, $E8, $C8, $C8, $C8, $C8, $E8, $E8, $18, $18, $08, $08
TitleTile16:
  db $4E, $4E, $CE, $CE, $9E, $9E, $3C, $3C, $F8, $F8, $F8, $F8, $BC, $BC, $DC, $DC
TitleTile17:
  db $5C, $5C, $5E, $5E, $5E, $5E, $2E, $2E, $2F, $2F, $2F, $2F, $17, $17, $17, $17
TitleTile18:
  db $17, $17, $0B, $0B, $0B, $0B, $0B, $0B, $05, $05, $05, $05, $04, $04, $03, $03
TitleTile19:
  db $80, $80, $C0, $C0, $C0, $C0, $E0, $E0, $F0, $F0, $F9, $F9, $F3, $F3, $E7, $E7
TitleTile20:
  db $60, $60, $C0, $C0, $C0, $C0, $80, $80, $00, $00, $00, $00, $00, $00, $00, $00
